=== MrHands/portfolio/src/project.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Project",
	"type": "object",
	"required": [
		"brief",
		"source",
		"title",
		"trailer"
	],
	"properties": {
		"brief": {
			"type": "object",
			"required": [
				"description",
				"employer",
				"platforms",
				"released",
				"role",
				"technologies",
				"type"
			],
			"properties": {
				"description": { "type": "string" },
				"employer": {
					"type": "string",
					"enum": [
						"bigpoint",
						"digc",
						"flexposure",
						"iec",
						"igad",
						"nixxes",
						"ubisoft"
					]
				},
				"platforms": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"linux",
							"mac",
							"ps4",
							"ps5",
							"steam",
							"uwp",
							"windows",
							"uplay",
							"xbone",
							"xbonex"
						]
					}
				},
				"released": { 
					"type": "string",
					"format": "date" 
				},
				"role": { "type": "string" },
				"stack": {
					"type": "array",
					"items": { "type": "string" }
				},
				"technologies": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"as",
							"c++",
							"cdc",
							"csharp",
							"g2",
							"horde3d",
							"coherent",
							"js",
							"ly",
							"opengl2",
							"opengl3",
							"phoenix",
							"qt",
							"scaleform",
							"ts",
							"ue3",
							"ue5"
						]
					}
				},
				"type": {
					"type": "string",
					"enum": [
						"software",
						"school",
						"aaa",
						"f2p",
						"indie",
						"mobile"
					]
				}
			}
		},
		"source": { "type": "string" },
		"title": { "type": "string" },
		"trailer": {
			"type": "object",
			"required": ["image"],
			"properties": {
				"image": { "type": "string" }
			}
		}
	}
}

=== MrHands/portfolio/src/lib/projects/rise-of-the-tomb-raider.json
{
	"title": "Rise of the Tomb Raider",
	"brief": {
		"type": "aaa",
		"role": "Systems Programmer",
		"description": "Implement keyboard and mouse controls on PC and integrated Razer Chroma features",
		"released": "2016-01-26",
		"employer": "nixxes",
		"platforms": [ "windows", "steam", "uwp" ],
		"technologies": [ "c++", "as", "scaleform", "cdc" ]
	},
	"trailer": {
		"link": "yt://PhGEFLcPHsY",
		"image": "rise-of-the-tomb-raider.jpg"
	},
	"source": "rise-of-the-tomb-raider.md"
}

=== MrHands/portfolio/src/projects/far-cry-6.json
{
	"title": "Far Cry 6",
	"brief": {
		"description": "As a Lead UI Programmer, I implemented features using a properietary UI framework and mentored several direct reports to help them achieve their OKRs.",
		"released": "2021-10-06",
		"employer": "ubisoft",
		"platforms": [ "uplay", "windows", "xbone", "xbonex", "ps4", "ps5" ],
		"technologies": [ "c++" ],
		"role": "UI Programmer",
		"type": "aaa",
		"stack": [ "Dunia" ]
	},
	"trailer": {
		"link": "yt://-IJuKT1mHO8",
		"image": "far-cry-6.jpg"
	},
	"source": "far-cry-6.md"
}

=== MrHands/portfolio/src/projects/procedural.json
{
	"title": "Procedural Design",
	"brief": {
		"type": "school",
		"role": "Student",
		"description": "School assignment about procedurally generated content.",
		"released": "2012-08-01",
		"employer": "igad",
		"platforms": [ "windows" ],
		"technologies": [ "c++", "opengl2" ]
	},
	"trailer": {
		"link": "",
		"image": "procedural.jpg"
	},
	"source": "procedural.md"
}

=== MrHands/portfolio/src/projects/lara-croft-and-the-temple-of-osiris.json
{
	"title": "Lara Croft and the Temple of Osiris",
	"brief": {
		"type": "aaa",
		"role": "Systems Programmer",
		"description": "As a Systems Programmer, I ensured the Steam version worked well with mouse and keyboard and designed the front-end for the text chat feature.",
		"released": "2014-12-01",
		"employer": "nixxes",
		"platforms": [ "steam", "windows", "ps4" ],
		"technologies": [ "cdc", "scaleform", "c++", "as" ]
	},
	"trailer": {
		"link": "yt://a4iiWCaI32g",
		"image": "lara-croft-and-the-temple-of-osiris.jpg"
	},
	"source": "lara-croft-and-the-temple-of-osiris.md"
}

=== MrHands/portfolio/src/lib/projects/skull-and-bones.json
{
	"title": "Skull & Bones",
	"brief": {
		"type": "aaa",
		"role": "Lead UI Programmer",
		"description": "Implemented online features, managed production priorities on the UI team, and mentored several direct reports",
		"released": "2024-02-13",
		"employer": "ubisoft",
		"platforms": [ "windows", "steam" ],
		"technologies": ["c++", "phoenix"]
	},
	"trailer": {
		"link": "yt://OmDYo7MbQxo",
		"image": "skull-and-bones.jpg"
	},
	"source": "skull-and-bones.md"
}

=== MrHands/portfolio/src/projects/game-of-thrones-seven-kingdoms.json
{
	"title": "Game of Thrones: Seven Kingdoms",
	"brief": {
		"type": "f2p",
		"role": "Senior UI Programmer",
		"description": "As a Senior UI Programmer, I built custom UI features for this free-to-play title, which was based on Amazon's Lumberyard engine.",
		"released": "2018-01-01",
		"employer": "bigpoint",
		"platforms": [ "windows" ],
		"technologies": [ "c++", "ly" ]
	},
	"trailer": {
		"image": "got.jpg"
	},
	"source": "game-of-thrones-seven-kingdoms.md"
}

=== MrHands/portfolio/src/lib/projects/game-of-thrones-seven-kingdoms.json
{
	"title": "Game of Thrones: Seven Kingdoms",
	"brief": {
		"type": "f2p",
		"role": "Senior UI Programmer",
		"description": "Built custom UI features for this free-to-play title using Amazon's Lumberyard engine",
		"released": "2018-01-01",
		"employer": "bigpoint",
		"platforms": [ "windows" ],
		"technologies": [ "c++", "ly" ]
	},
	"trailer": {
		"image": "got.jpg"
	},
	"source": "game-of-thrones-seven-kingdoms.md"
}

=== MrHands/portfolio/src/lib/projects/thief.json
{
	"title": "Thief",
	"brief": {
		"type": "aaa",
		"role": "Systems Programmer",
		"description": "Implemented keyboard and mouse support and map navigation on PC",
		"released": "2014-02-01",
		"employer": "nixxes",
		"platforms": [ "steam" ],
		"technologies": [ "c++", "as", "scaleform", "ue3" ]
	},
	"trailer": {
		"link": "yt://6FtOFv5oGEI",
		"image": "thief.jpg"
	},
	"source": "thief.md"
}
