=== MrHands/portfolio/src/project.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Project",
	"type": "object",
	"required": [
		"brief",
		"source",
		"title",
		"trailer"
	],
	"properties": {
		"brief": {
			"type": "object",
			"required": [
				"description",
				"employer",
				"platforms",
				"released",
				"role",
				"technologies",
				"type"
			],
			"properties": {
				"description": { "type": "string" },
				"employer": {
					"type": "string",
					"enum": [
						"bigpoint",
						"digc",
						"flexposure",
						"iec",
						"igad",
						"nixxes",
						"ubisoft"
					]
				},
				"platforms": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"linux",
							"mac",
							"ps4",
							"ps5",
							"steam",
							"uwp",
							"windows",
							"uplay",
							"xbone",
							"xbonex"
						]
					}
				},
				"released": { 
					"type": "string",
					"format": "date" 
				},
				"role": { "type": "string" },
				"stack": {
					"type": "array",
					"items": { "type": "string" }
				},
				"technologies": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"as",
							"c++",
							"cdc",
							"csharp",
							"g2",
							"horde3d",
							"coherent",
							"js",
							"ly",
							"opengl2",
							"opengl3",
							"phoenix",
							"qt",
							"scaleform",
							"ts",
							"ue3",
							"ue5"
						]
					}
				},
				"type": {
					"type": "string",
					"enum": [
						"software",
						"school",
						"aaa",
						"f2p",
						"indie",
						"mobile"
					]
				}
			}
		},
		"source": { "type": "string" },
		"title": { "type": "string" },
		"trailer": {
			"type": "object",
			"required": ["image"],
			"properties": {
				"image": { "type": "string" }
			}
		}
	}
}

=== MrHands/portfolio/src/lib/projects/dolphin-dreams.json
{
	"title": "Dolphin Dreams",
	"brief": {
		"type": "school",
		"role": "Intern",
		"description": "Optimized and implemented new features on a serious game project for children with severe mental disabilities",
		"released": "2012-09-01",
		"employer": "digc",
		"platforms": [ "windows" ],
		"technologies": [ "c++", "horde3d", "opengl2" ]
	},
	"trailer": {
		"image": "dolphin-dreams.jpg"
	},
	"source": "dolphin-dreams.md"
}

=== MrHands/portfolio/src/lib/projects/lara-croft-and-the-temple-of-osiris.json
{
	"title": "Lara Croft and the Temple of Osiris",
	"brief": {
		"type": "aaa",
		"role": "Systems Programmer",
		"description": "Implemented input handling for menus and coop functionality on the PC version",
		"released": "2014-12-01",
		"employer": "nixxes",
		"platforms": [ "steam", "windows", "ps4" ],
		"technologies": [ "cdc", "scaleform", "c++", "as" ]
	},
	"trailer": {
		"link": "yt://a4iiWCaI32g",
		"image": "lara-croft-and-the-temple-of-osiris.jpg"
	},
	"source": "lara-croft-and-the-temple-of-osiris.md"
}

=== MrHands/portfolio/src/projects/relativity.json
{
	"title": "Relativity",
	"brief": {
		"type": "school",
		"description": "Networked real-time strategy game in which multiple factions fight over control of time itself.",
		"released": "2010-08-01",
		"employer": "igad",
		"role": "Team Lead",
		"platforms": [ "windows" ],
		"technologies": [ "c++", "opengl2", "qt" ]
	},
	"trailer": {
		"link": "yt://64vjOvDIamg",
		"image": "relativity.jpg"
	},
	"source": "relativity.md"
}

=== MrHands/portfolio/src/projects/flinq4.json
{
	"title": "FlinQ 4.0",
	"brief": {
		"type": "software",
		"role": "Junior Developer",
		"description": "Security management package that combines reports from multiple sources into a single and intuitive 3D interface.",
		"released": "2013-09-01",
		"employer": "flexposure",
		"platforms": [ "windows", "mac" ],
		"technologies": [ "c++", "csharp", "opengl3" ]
	},
	"trailer": {
		"link": "yt://IjLIkTY32VM",
		"image": "flinq4.jpg"
	},
	"source": "flinq4.md"
}

=== MrHands/portfolio/src/projects/deus-ex-mankind-divided.json
{
	"title": "Deus Ex: Mankind Divided",
	"brief": {
		"type": "aaa",
		"role": "Systems Programmer",
		"description": "As a Systems Programmer, I implemented several key features for the Steam version, including the weapons bar and the key rebinding screen.",
		"released": "2016-08-23",
		"employer": "nixxes",
		"platforms": [ "steam", "windows" ],
		"technologies": [ "g2", "scaleform", "c++", "as" ],
		"stack": [ "Dawn Engine", "Autodesk Scaleform", "ActionScript 3" ]
	},
	"trailer": {
		"link": "yt://CfV01sTqB68",
		"image": "deus-ex-mankind-divided.jpg"
	},
	"source": "deus-ex-mankind-divided.md"
}

=== MrHands/portfolio/src/projects/dolphin-dreams.json
{
	"title": "Dolphin Dreams",
	"brief": {
		"type": "school",
		"role": "Intern",
		"description": "Serious game project designed to aid children with severe mental disabilities.",
		"released": "2012-09-01",
		"employer": "digc",
		"platforms": [ "windows" ],
		"technologies": [ "c++", "horde3d", "opengl2" ]
	},
	"trailer": {
		"image": "dolphin-dreams.jpg"
	},
	"source": "dolphin-dreams.md"
}

=== MrHands/portfolio/src/lib/projects/flinq4.json
{
	"title": "FlinQ 4.0",
	"brief": {
		"type": "software",
		"role": "Junior Developer",
		"description": "Implemented UI features and device drivers for a 3D security management package",
		"released": "2013-09-01",
		"employer": "flexposure",
		"platforms": [ "windows", "mac" ],
		"technologies": [ "c++", "csharp", "opengl3" ]
	},
	"trailer": {
		"link": "yt://IjLIkTY32VM",
		"image": "flinq4.jpg"
	},
	"source": "flinq4.md"
}

=== MrHands/portfolio/src/lib/projects/deus-ex-mankind-divided.json
{
	"title": "Deus Ex: Mankind Divided",
	"brief": {
		"type": "aaa",
		"role": "Systems Programmer",
		"description": "Implemented several UI features on PC, including the weapons bar and the key rebinding screen",
		"released": "2016-08-23",
		"employer": "nixxes",
		"platforms": [ "steam", "windows" ],
		"technologies": [ "g2", "scaleform", "c++", "as" ],
		"stack": [ "Dawn Engine", "Autodesk Scaleform", "ActionScript 3" ]
	},
	"trailer": {
		"link": "yt://CfV01sTqB68",
		"image": "deus-ex-mankind-divided.jpg"
	},
	"source": "deus-ex-mankind-divided.md"
}
