=== MrHands/portfolio/src/project.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Project",
	"type": "object",
	"required": [
		"brief",
		"source",
		"title",
		"trailer"
	],
	"properties": {
		"brief": {
			"type": "object",
			"required": [
				"description",
				"employer",
				"platforms",
				"released",
				"role",
				"technologies",
				"type"
			],
			"properties": {
				"description": { "type": "string" },
				"employer": {
					"type": "string",
					"enum": [
						"bigpoint",
						"digc",
						"flexposure",
						"iec",
						"igad",
						"nixxes",
						"ubisoft"
					]
				},
				"platforms": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"linux",
							"mac",
							"ps4",
							"ps5",
							"steam",
							"uwp",
							"windows",
							"uplay",
							"xbone",
							"xbonex"
						]
					}
				},
				"released": { 
					"type": "string",
					"format": "date" 
				},
				"role": { "type": "string" },
				"stack": {
					"type": "array",
					"items": { "type": "string" }
				},
				"technologies": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"as",
							"c++",
							"cdc",
							"csharp",
							"g2",
							"horde3d",
							"coherent",
							"js",
							"ly",
							"opengl2",
							"opengl3",
							"phoenix",
							"qt",
							"scaleform",
							"ts",
							"ue3",
							"ue5"
						]
					}
				},
				"type": {
					"type": "string",
					"enum": [
						"software",
						"school",
						"aaa",
						"f2p",
						"indie",
						"mobile"
					]
				}
			}
		},
		"source": { "type": "string" },
		"title": { "type": "string" },
		"trailer": {
			"type": "object",
			"required": ["image"],
			"properties": {
				"image": { "type": "string" }
			}
		}
	}
}

=== MrHands/portfolio/src/projects/rise-of-the-tomb-raider.json
{
	"title": "Rise of the Tomb Raider",
	"brief": {
		"type": "aaa",
		"role": "Systems Programmer",
		"description": "As a Systems Programmer, I ensured the Steam version worked well with mouse and keyboard and integrated Razer Chroma features.",
		"released": "2016-01-26",
		"employer": "nixxes",
		"platforms": [ "windows", "steam", "uwp" ],
		"technologies": [ "c++", "as", "scaleform", "cdc" ]
	},
	"trailer": {
		"link": "yt://PhGEFLcPHsY",
		"image": "rise-of-the-tomb-raider.jpg"
	},
	"source": "rise-of-the-tomb-raider.md"
}

=== MrHands/portfolio/src/projects/thief.json
{
	"title": "Thief",
	"brief": {
		"type": "aaa",
		"role": "Systems Programmer",
		"description": "As a Systems Programmer, I ensured the in-game map in the Steam version worked well with mouse and keyboard.",
		"released": "2014-02-01",
		"employer": "nixxes",
		"platforms": [ "steam" ],
		"technologies": [ "c++", "as", "scaleform", "ue3" ]
	},
	"trailer": {
		"link": "yt://6FtOFv5oGEI",
		"image": "thief.jpg"
	},
	"source": "thief.md"
}

=== MrHands/portfolio/src/lib/projects/far-cry-6.json
{
	"title": "Far Cry 6",
	"brief": {
		"description": "Implemented features using a proprietary UI framework and managed several direct reports",
		"released": "2021-10-06",
		"employer": "ubisoft",
		"platforms": [ "uplay", "windows", "xbone", "xbonex", "ps4", "ps5" ],
		"technologies": [ "c++" ],
		"role": "UI Programmer",
		"type": "aaa",
		"stack": [ "Dunia" ]
	},
	"trailer": {
		"link": "yt://-IJuKT1mHO8",
		"image": "far-cry-6.jpg"
	},
	"source": "far-cry-6.md"
}
